# to do: same as original

# Model structure
num_regions: 2
num_neurons_per_region: 20

# latents per cell type [E, I]
cell_type_latents: [2, 2]

# dynamics config
dynamics:
  within_region: true
  across_region: true
  base_strength: 0.95
  noise_scale: 0.1
  use_qp: true

# emissions config
emissions:
  use_unit_norm: true
  clip_bounds: [-1.0, 1.0]
